### ISSUE TITLE
Close in favour of wpcv-woo-civi-integration ??

### ISSUE THREAD

**Issue by JoeMurray** [veda-consulting/woocommerce_civicrm#50]
@mecachisenros I see you have been contributing to https://github.com/WPCV/wpcv-woo-civi-integration/graphs/contributors as well as this repo https://github.com/mecachisenros/woocommerce_civicrm/graphs/contributors. Can you detail the differences between the two integrations and reasons for maintaining both rather than focussing our efforts on wpcv-woo-CiviCRM-integration ? The latter seems to have had a lot more commits in last 6 months. @christianwach what are your thoughts on facilitating collaboration?

**Comment by christianwach** [comment]
@JoeMurray None of us have heard from Andrei for a few months now - it seems as though he's retired from CiviCRM/WordPress coding and has moved on to other things. 

I can explain the history of these repos however...

Andrei didn't want to continue to be solely responsible for maintaining and developing this plugin, so I created the WPCV account to facilitate responsibility being shared between [a few folks](https://github.com/orgs/WPCV/people) with an interest in doing so (initially @kcristiano @danaskallman @mecachisenros and myself). FWIW I also plan to move some of my plugins over to that account at some point, for similar reasons.

Andrei pushed the code from here to the new repo as a remote to maintain the commit history. If you look at the [contributor graph on the WPCV repo](https://github.com/WPCV/wpcv-woo-civi-integration/graphs/contributors) you'll see that it is identical to this one's up to the point where I started working on it.

The net result is that I took the current state of this repo as my starting point and continued development over there with a view to getting the plugin ready for submission to the WordPress Plugin Directory. FWIW, this plugin would not have stood any chance at all of being accepted because:

* The WordPress Plugin Directory has strict rules about naming which this plugin contravenes.
* This plugin is... um... _buggy_ in so many ways and doesn't really do what it says it should.

So the [Integrate CiviCRM with WooCommerce](https://github.com/WPCV/wpcv-woo-civi-integration) plugin _is_ this plugin, but better. It has a migration page which will convert the existing metadata to the new schema, so there's really no reason not to move over to Integrate CiviCRM with WooCommerce. 

I hope to have time this week to submit it to the WordPress Plugin Directory, though there may still be a stumbling block due to its AGPL license. We'll see what the WordPress folks say.

**Comment by JoeMurray** [comment]
Thanks very much for the helpful background. We'll be moving this over.

**Comment by christianwach** [comment]
Oh, one more thing @JoeMurray - Andrei hasn't been active on GitHub since April 27, 2021... and since he's the sole admin of this repo, it can't be made read-only or modified. I guess the only option is to have a prominent issue that points people to [Integrate CiviCRM with WooCommerce](https://github.com/WPCV/wpcv-woo-civi-integration) instead.
